### ISSUE TITLE
[Question] Is there a proper way to control modern laser printers to print on dot level?

### ISSUE THREAD

**Issue by Wikinaut** [intra2net/paperbackup#7]
Do you know a way to control modern laser printers (I use Brother MFC-9342CDW) so that they print really "dot-by-dot" ?

**Comment by intra2net** [comment]
Back in the days, there was a raster image processor (RIP) and it's job was to convert stuff like postscript to a exact raster image which was then printed by the printer. The RIP had to be matched to the printer and the data flow between RIP and printer was usually proprietary. Usually you had many options and settings you could tweak on the RIP and were able to get pixel-perfect printouts.

Now the RIP is usually integrated into the printer and you just have very few options you can tweak. Also the printer do tricks like half-dots which further blurs the lines.

Only film exposer equipment still has RIPs with pixel-exact exposure.

So I guess you have to tweak your printout by moving and scaling the picture a bit and analyzing the results under maginfication.

**Comment by Wikinaut** [comment]
@intra2net I came from the "stone age" and in the early 80ies we could exactly control (print with) each **needle** of the 8-, later 24-pin needle printers (EPSON FX-80, MX-80, NEC P6...) when we sent the correct binary data to the printer. It would be a great improvement for our "PaperBack" projects when this would be possible with the Laser Printers, too.

I will try to contact Brother.

**Comment by intra2net** [comment]
Nothing paperbackup can fix, so closing this now.
