### ISSUE TITLE
Questions regarding this solution for backup

### ISSUE THREAD

**Issue by DonaldTsang** [intra2net/paperbackup#9]
1. Is it made just for backing up keys, or can it store larger pieces of data?
2. Does it store everything on only one large QR code?

**Comment by intra2net** [comment]
1. You can also store larger pieces of data, not just small blocks. But be aware that you can't use it directly for binary data and some characters like ^ are used to encode blocks. So you should probably encode your data with base64 first.

2. No, it uses several smaller QR codes. See https://github.com/intra2net/paperbackup/blob/master/example_output.pdf for an example. If a QR code gets too large, some programs get problems decoding it properly.
